front/src/App.jsx, front/src/components/catalogo/Catalogo.jsx, front/src/components/catalogo/Detail.jsx, front/src/components/catalogo/Filters.jsx, front/src/components/catalogo/Orders.jsx, front/src/components/catalogo/Posters.jsx, front/src/components/catalogo/SearchBar.jsx, front/src/components/catalogo/Styles/catalogo.js, front/src/main.jsx
=> Routes config

front/src/components/catalogo/SearchBar.jsx
falta crear action, y case en reducer
=> search basico sin dispatch a la action

front/src/components/catalogo/Orders.jsx, front/src/redux/action.js, front/src/redux/reducer.js
Ordenamiento basico sin estilos
action y reducer  getAllBooks(por ahi es lo mismo que hizo Kelvin, pero no encontraba la forma de tener un array con toda la info para hacer el ordenamiento - igual lo de Kelvin no lo toque, solo agregue lo mio debajo de lo de el)
el reducer del sortByRating esta hecho en base al precio, ya que aun no hay reseñas para hacerlo
=> basic order without actions

api/src/controllers/books/getBookById.js, api/src/handlers/bookHandler.js, api/src/handlers/getBookByIdHandler.js, api/src/models/Book.js, api/src/routes/bookRouter.js
=> creación de getById del Detail

front/src/components/catalogo/Detail.jsx, front/src/redux/reducer.js
Agrege un globalState en la store, y la asocie a una variable en Detail, desde donde saco toda la data para renderizar
=> Refactor(Detail & Reducer) 

front/src/components/catalogo/SearchBar.jsx, front/src/redux/action.js, front/src/redux/reducer.js
la imagen de la validacion es random se cambiaria por una alerta personalizada, la el endpoint de la action tambien debe modificarse por la ruta del back
=> search con action, reducer y validacion

api/src/controllers/books/getAllBooks.js, api/src/controllers/books/searchBooks.js, api/src/handlers/bookHandler.js, api/src/routes/bookRouter.js
Search bar funcionando solo por titulo hasta tanto se complete la carga en base de datos.
=> get all & search bar

front/src/components/catalogo/Orders.jsx, front/src/redux/reducer.js
cambie el estado global para guardar el ordenamiento(tambien el search, pero no lo puedo probar) en relacion al estado global utilizado en catalogo
=> ordenamiento funcionando

front/src/components/catalogo/SearchBar.jsx, front/src/components/catalogo/Styles/catalogo.js, front/src/components/nav/Nav.jsx
Hice la barra basica del catalogo
=> nav del catalogo

api/src/controllers/books/getBookById.js
Modifico el controlador getBookById para incorporar los modelos Author y Gender.
=> modifico getBookById para autor y género

front/src/components/catalogo/Card.jsx, front/src/components/catalogo/Catalogo.jsx, front/src/components/catalogo/Detail.jsx, front/src/components/catalogo/Paginado.jsx, front/src/components/catalogo/Posters.jsx, front/src/components/catalogo/Styles/catalogo.js, front/src/redux/action.js, front/src/redux/reducer.js
Dos commits, actualizacion de catalogo y refactorizacion de logica de los Sorts.
=> Catalogo + Paginador + Refactor de ReduxSorts + Detail funcional

front/src/components/catalogo/Orders.jsx, front/src/components/catalogo/SearchBar.jsx, front/src/components/catalogo/Styles/catalogo.js
Vuelven a pagina 1 search y ordenamiento
=> Search y Ordenamiento Paginado

front/src/components/catalogo/Filters.jsx, front/src/components/catalogo/Orders.jsx, front/src/redux/reducer.js
ordenamiento en todas las paginas
filtro funciona el all(todos)
=> arreglos en ordenamiento y filtros

api/src/app.js
ser cambia el puerto de conexión para el front
=> puerto front

front/src/components/catalogo/Filters.jsx, front/src/redux/reducer.js
los filtros toman el paginado, pero hay un problema al renderizar en el primer click, viene atrasado 1 click, entonces la primer pagina se renderiza mal... si alguien lo puede ver y encuentra el error buenisimo, sino lo sigo investigando mañana...
NOTA: al lograr paginar perdi que quede seleccionado el value en el filter(1er commit)
=> filtrado con paginado- ver comentarios/commits

api/src/handlers/bookHandler.js, front/src/redux/reducer.js
=> paginado del search 

front/src/components/catalogo/Filters.jsx
Creación del botón de borrado de los filtros de géneros y autores.
=> creación de botón borrado de filtros

api/src/controllers/books/createBook.js, api/src/handlers/createBookHandler.js, api/src/routes/bookRouter.js
Se crea la ruta con metodo post para la creacion de nuevos libros mediante form
=> creacion ruta createBook

front/src/components/catalogo/Filters.jsx, front/src/redux/reducer.js
se arreglo los select que cuando se borre formulario vuelvan a all
=> fix- select de filtro, vuelve a all cuando hace reset

front/src/redux/reducer.js
termine de limpiar estados inutilizados y comente todos los arrays para la claridad.
=> Refactor Reducer, 

front/src/components/catalogo/Detail.jsx, front/src/components/reviews/ContainerReviews.jsx
Nota: no puede probar su funcionamiento porque no levanta el servidor
=> rederizado modal de containerReviews con click en btn star de detail

api/src/controllers/auth/gmail.js, api/src/controllers/auth/local.js, api/src/routes/bookRouterAuth.js
- creo usuario usando gmail
- si el usuario fue creado por local no 
permito que lo cree por gmail
=> crear usuario con gmail

api/src/controllers/auth/local.js, api/views/login.ejs, api/views/registro.ejs
cambie nombre de variable para que anda el fomulario
=> cambie nombre de variable

api/package.json, api/src/controllers/auth/gmail.js, api/src/controllers/auth/local.js, api/src/handlers/auth/loginHandler.js, api/src/routes/bookRouterAuth.js
se debe ejecutar npm i en la carpeta api
creo usuario con formulario y gmail
logeo  para ambos, no permito duplicidad ni si lo creo con gmail poder crearlo con formulario
=> creo usuario y logueo con gmail y formulario rta JSON

api/src/models/Author.js, api/src/models/Book.js, api/src/models/Gender.js, api/src/models/Review.js, api/src/models/User.js, front/package-lock.json, front/package.json, front/src/components/formCreateBook/validation.js
Agregué validaciones a todos los modelos de la base de datos.
Sumé el atribito "lastName" al modelo user.
Corregí el archivo "validation" del formCreateBook con expresiones que faltaban.
=> validaciones y ajustes a los modelos + lastName a User

api/index.js, api/src/controllers/auth/gmail.js, api/src/controllers/auth/local.js, api/src/handlers/auth/loginHandler.js, api/src/routes/bookRouterAuth.js, api/views/registro.ejs
devuelvo JSON de login con first name y last
=> devuelvo JSON de login con first name y last

api/index.js, userReviews.txt
actualizacion userReviews para carga de base de datos
=> actualizacion userReviews para carga de base de datos

api/src/controllers/auth/local.js, api/views/registro.ejs
creo el el first name en el registro, mediante formulario local
=> creo el el first name en el registro, mediante formulario local

front/src/components/reviews/FormCreateReview.jsx, front/src/components/reviews/validation.js
Y también se acomodaron paréntesis y lleves en el return del archivo formCreateReview.
=> Ajustes a formCreateReview y validation

front/src/components/adminDashboard/FormEditBook.jsx, front/src/components/adminDashboard/Inventario.jsx
Agregue el filtrado, estilos y utils para el boton de Edit.
Cree el primer boceto del componente FormEditBook.
=> NewCode(adminDashboard/Inventario)

api/src/handlers/reviews/deleteReviewHandler.js, api/src/handlers/reviews/editReviewHandler.js, api/src/routes/reviewsRouter.js, userReviews.txt
se modifica forma de enviar info de reviews (cambio a params)****
=> se modifica forma de enviar info de reviews (cambio a params)

api/package.json, api/src/app.js, api/src/controllers/auth/gmail.js, api/src/controllers/auth/local.js, api/src/routes/bookRouterAuth.js
espero la respuesta de gmail y despues decido que hago
=> fix back auth gmail

api/src/handlers/book/updateBookHandler.js, api/src/models/Book.js, api/src/routes/bookRouter.js, front/src/components/adminDashboard/FormEditBook.jsx, front/src/components/adminDashboard/Inventario.jsx, front/src/redux/action.js, front/src/redux/reducer.js
El back fue refactorizado para que funcione el PUT de los libros. El componente inventario tiene todas sus funcionalidades, excepto el borrado logico. Faltan estilos al updateForm.
=> Refactor&NewCode(Front:Redux e inventario. Back: bookModel/bookRouter/updatebookHandler)

api/src/models/Review.js, front/src/components/formCreateBook/formCreateBook.jsx
Se colocacion corchetes que faltaban en el modelo Review y se le dió estilo a las validaciones del formulario.
=> corrección de modelo Review y formCreateBook

front/src/components/adminDashboard/FormEditBook.jsx
Se cambio tipo de input de stock y price a number
Se borra parseo de estos inputs
=> correccion formulario de edicion de libros (front)

front/src/components/UserDashboard/myReviews/FormEditReviews.jsx, front/src/components/UserDashboard/myReviews/MyReviewsContainer.jsx, front/src/components/reviews/ContainerReviews.jsx, front/src/components/reviews/FormCreateReview.jsx, front/src/redux/action.js, front/src/redux/reducer.js
Nota: al enviar el formulario no se reflejan los cambios, mañana lo sigo viendo
=> formulario editReviews- renderizado condicional por delete, tanto en reseñas por usuario como por libro

front/src/components/UserDashboard/myReviews/FormEditReviews.jsx, front/src/components/UserDashboard/myReviews/MyReviewsContainer.jsx, front/src/components/aboutUs/AboutUs.jsx, front/src/components/adminDashboard/Menu.jsx, front/src/components/catalogo/Card.jsx, front/src/components/catalogo/Detail.jsx, front/src/components/reviews/FormCreateReview.jsx, front/src/components/reviews/Review.jsx
Detalles que se hablaron en la meet
Button reseñas rectangular
Comento button Agregar a wishlist
Agrego algo sobre nosotros
Agrego keys que faltaban
Comento secciones del panel de admin
=> detalles charlados en meet

api/index.js, api/package.json, api/src/db.js, front/ruta.js, front/src/App.jsx, front/src/components/login/Login.jsx, front/src/components/login/Registro.jsx, front/src/redux/action.js
=> first commit

api/package.json, api/src/controllers/users/passwordResetReq.js, api/src/controllers/users/passwordResetRes.js, api/src/handlers/mailing/mailing.js, api/src/handlers/users/passwordResetReqHandler.js, api/src/handlers/users/passwordResetResHandler.js, api/src/routes/MailingRouter.js, api/src/routes/userRouter.js, front/vite.config.js
Se crean 2 etapas de restablecimiento de contraseña. 
1. Solicitud de restablecimiento. (envía el correo)
2.  Cambio de contraseña. 
Se debe instalar jsonwebtoken en backend
=> creacion de rutas de reestablecimiento de password

api/src/controllers/users/passwordResetReq.js, api/src/controllers/users/passwordResetRes.js, api/src/handlers/mailing/mailing.js
se agrega mail de confirmacion de cambio de contrasenia
=> se agrega mail de confirmacion de cambio de contrasenia

api/src/controllers/orders/createOrder.js, api/src/handlers/order/createOrderHandler.js, api/src/routes/index.js, api/src/routes/orderRouter.js
Se crea la ruta post para el guardado de la orden al realizar la confirmación del carrito
http://localhost:3001/order
=> post order con details

api/src/controllers/orders/getAllHistory.js
Se agrega a la orden el atributo id del usuario que hizo la compra.
=> Fix/1 con el agregado de id_user en getAllHistory de ordenes

.gitignore, api/src/routes/bookRouterAuth.js, front/vercel.json
si no coloca telefono le fuerzo uno
=> se coloca fijo telefono 1234567890

front/src/App.jsx, front/src/components/UserDashboard/DetailByBook.jsx, front/src/components/UserDashboard/MiSuscripcion.jsx, front/src/components/UserDashboard/MyShopping.jsx, front/src/components/UserDashboard/Profile.jsx, front/src/components/login/Ingreso.jsx, front/src/redux/action.js, front/src/redux/reducer.js
Dejo preparado redux para cuando la ruta traiga los datos necesarios
Mi suscripcion hardcodeada, falta terminar de aplicar estilos
=> Mi suscripcion-Vir

api/package.json, api/src/app.js, api/src/routes/index.js, api/src/routes/mercadoPagoRouter.js, front/src/components/shoppingCart/CartContainer.jsx, front/vite.config.js
Se incorpora funcionalidad de pasarela de pago luego de confirmar carrito
Se debe hacer npm install en el back
Se pasan credenciales de de .env por trello
=> mercado pago

front/src/components/nav/Nav.jsx
creo el  local storage de gmail
creo un estado local para ver si el useEffect es por el redicionamiento de gmail o un f5.
=> permanencia login

api/src/controllers/users/passwordResetReq.js, front/src/components/login/FormResetPass.jsx
oculto boton restablecer contraseña
y cambio el texto titulo
=> oculto boton restablecer contraseña

api/src/routes/bookRouterAuth.js, front/src/redux/reducer.js
elimino la palabra usuario  cuando se logeaba por gmail y ibas a editar telefono
=> elimino la palabra usuario en telefono - y elimino pagina detalle cuando cambia de pagina

api/src/handlers/users/updateUserHandler.js
permito poner null en editar telefono telefono
=> phone null en editar

front/src/components/adminDashboard/Orders.jsx, front/src/components/adminDashboard/Users.jsx, front/src/redux/action.js, front/src/redux/reducer.js
Admin/Orders=> linkeado al mailing al editar el estado de la orden a "Despachada", altere las actions para que funcione un bug que encontre en Admin/users.
adminDashboard/Orders => Filtro x Estado Funcional
=> adminDashboard/Orders => filtro y mailing // Admin/User bugFix

front/src/components/adminDashboard/Inventario.jsx, front/src/components/adminDashboard/Orders.jsx, front/src/components/adminDashboard/Users.jsx, front/src/components/catalogo/Detail.jsx
Se agrega portada al detalle.
Se ajusta el texto de Order, Users e Inventario.
Borro imagenes de portada que se subieron a mi carpeta uploads (portada de libros).
Cambio el estado Active a Activo y Blocked a Bloqueado en Gestión de Usuarios (Dashboard).
=> Portada+Dashborad

front/src/redux/reducer.js
=> search bar arreglo
